// Compiled shader for PC, Mac & Linux Standalone

//////////////////////////////////////////////////////////////////////////
// 
// NOTE: This is *not* a valid shader file, the contents are provided just
// for information and for debugging purposes only.
// 
//////////////////////////////////////////////////////////////////////////
// Skipping shader variants that would not be included into build of current scene.

Shader "Hidden/NewImageEffectShader" {
Properties {
 _MainTex ("Texture", 2D) = "white" { }
}
SubShader { 


 // Stats for Vertex shader:
 //         d3d9: 10 math
 //        d3d11: 8 math
 // Stats for Fragment shader:
 //         d3d9: 1 math, 1 texture
 //        d3d11: 1 math, 1 texture
 Pass {
  ZTest Always
  ZWrite Off
  Cull Off
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
No keywords set in this variant.
-- Vertex shader for "d3d9":
// Stats: 10 math
Uses vertex data channel "Vertex"
Uses vertex data channel "TexCoord"

Matrix4x4 unity_MatrixVP at 4
Matrix4x4 unity_ObjectToWorld at 0

Shader Disassembly:
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   row_major float4x4 unity_MatrixVP;
//   row_major float4x4 unity_ObjectToWorld;
//
//
// Registers:
//
//   Name                Reg   Size
//   ------------------- ----- ----
//   unity_ObjectToWorld c0       4
//   unity_MatrixVP      c4       4
//

    vs_3_0
    def c8, 1, 0, 0, 0
    dcl_position v0
    dcl_texcoord v1
    dcl_texcoord o0.xy
    dcl_position o1
    mad r0, v0.xyzx, c8.xxxy, c8.yyyx
    dp4 r1.x, c0, r0
    dp4 r1.y, c1, r0
    dp4 r1.z, c2, r0
    dp4 r1.w, c3, r0
    dp4 r2.x, c4, r1
    dp4 r2.y, c5, r1
    dp4 r2.z, c6, r1
    dp4 r2.w, c7, r1
    mov o0.xy, v1
    mad o1.xy, r2.w, c255, r2
    mov o1.zw, r2

// approximately 12 instruction slots used


-- Fragment shader for "d3d9":
// Stats: 1 math, 1 textures
Set 2D Texture "_MainTex" to slot 0

Shader Disassembly:
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   sampler2D _MainTex;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   _MainTex     s0       1
//

    ps_3_0
    def c0, 1, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    texld_pp r0, v0, s0
    add_pp oC0, -r0, c0.x

// approximately 2 instruction slots used (1 texture, 1 arithmetic)


-- Vertex shader for "d3d11":
// Stats: 8 math, 2 temp registers
Uses vertex data channel "Vertex"
Uses vertex data channel "TexCoord"

Constant Buffer "UnityPerDraw" (160 bytes) on slot 0 {
  Matrix4x4 unity_ObjectToWorld at 0
}
Constant Buffer "UnityPerFrame" (368 bytes) on slot 1 {
  Matrix4x4 unity_MatrixVP at 272
}

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyz 
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// SV_POSITION              0   xyzw        1      POS   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[4], immediateIndexed
      dcl_constantbuffer CB1[21], immediateIndexed
      dcl_input v0.xyz
      dcl_input v1.xy
      dcl_output o0.xy
      dcl_output_siv o1.xyzw, position
      dcl_temps 2
   0: mov o0.xy, v1.xyxx
   1: mul r0.xyzw, v0.yyyy, cb0[1].xyzw
   2: mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
   3: mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
   4: add r0.xyzw, r0.xyzw, cb0[3].xyzw
   5: mul r1.xyzw, r0.yyyy, cb1[18].xyzw
   6: mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
   7: mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
   8: mad o1.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
   9: ret 
// Approximately 0 instruction slots used


-- Fragment shader for "d3d11":
// Stats: 1 math, 1 temp registers, 1 textures
Set 2D Texture "_MainTex" to slot 0

Shader Disassembly:
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// SV_POSITION              0   xyzw        1      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_sampler s0, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_input_ps linear v0.xy
      dcl_output o0.xyzw
      dcl_temps 1
   0: sample r0.xyzw, v0.xyxx, t0.xyzw, s0
   1: add o0.xyzw, -r0.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
   2: ret 
// Approximately 0 instruction slots used


 }
}
}